dist: xenial
language: c++
compiler: g++ -std=c++14

script:
  - make
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files tests/testGameClass.cpp | xargs clang-format -i && git diff --exit-code
  - ./bin/program