dist: xenial
language: c++
compiler: g++

script:
  - make
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files tests/testGameClass.cpp | xargs clang-format -i && git diff --exit-code
  - ./bin/program